# Generated by Django 5.1 on 2024-09-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalbudgets", "0003_rename_amount_personalbudget_total_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalbudget",
            name="category",
        ),
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="item",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
