# Generated by Django 5.1 on 2024-09-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalbudgets", "0006_alter_personalbudget_id_alter_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalbudget",
            name="budget",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
