# Generated by Django 5.1 on 2024-09-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalbudgets", "0007_personalbudget_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalbudget",
            name="status",
            field=models.CharField(
                choices=[("Expired", "Expired"), ("Not Expired", "Not Expired")],
                default="Not Expired",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="personalbudget",
            name="validity",
            field=models.DateField(default="2024-09-29"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="remaining_installment",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("Paid", "Paid"), ("To Pay", "To Pay")],
                default="To Pay",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="validity",
            field=models.DateField(default="2024-09-29"),
            preserve_default=False,
        ),
    ]
