# Generated by Django 5.1 on 2024-09-29 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "personalbudgets",
            "0008_personalbudget_status_personalbudget_validity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalbudget",
            name="validity",
            field=models.DateField(default="2024-09-29"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="validity",
            field=models.DateField(default="2024-09-29"),
        ),
    ]
