# Generated by Django 5.1 on 2024-09-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalbudgets", "0010_alter_personalbudget_validity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="validity",
            field=models.DateField(default="2024-09-29"),
        ),
    ]
