# Generated by Django 5.1 on 2024-09-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalbudgets", "0011_alter_transaction_validity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalbudget",
            name="validity",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="validity",
            field=models.DateField(),
        ),
    ]
