# Generated by Django 5.1 on 2024-10-05 20:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalbudgets", "0012_alter_personalbudget_validity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="personalbudget",
            name="budget",
        ),
        migrations.AddField(
            model_name="personalbudget",
            name="name",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="personalbudgets.category",
            ),
        ),
    ]
