# Generated by Django 5.1 on 2024-10-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personalbudgets", "0014_personalbudget_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalbudget",
            old_name="name",
            new_name="budget",
        ),
    ]
