# Generated by Django 5.1 on 2024-10-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalbudgets", "0015_rename_name_personalbudget_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalbudget",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="personalbudget",
            name="remaining_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="personalbudget",
            name="status",
            field=models.CharField(
                choices=[("Expired", "Expired"), ("Not Expired", "Not Expired")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("Paid", "Paid"), ("To Pay", "To Pay")], max_length=20
            ),
        ),
    ]
