# Generated by Django 5.1 on 2024-10-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalbudgets", "0019_category_notes_category_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="goal",
            old_name="date",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="personalbudget",
            old_name="date",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="date",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateField(auto_now_add=True, default="2024-10-06"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateField(default="2024-10-06"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goal",
            name="created_at",
            field=models.DateField(auto_now_add=True, default="2024-10-06"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goal",
            name="peding_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="goal",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalbudget",
            name="created_at",
            field=models.DateField(auto_now_add=True, default="2024-10-06"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="created_at",
            field=models.DateField(auto_now_add=True, default="2024-10-06"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goal",
            name="status",
            field=models.CharField(
                choices=[
                    ("To Complete", "To Complete"),
                    ("Completed", "Completed"),
                    ("Not Completed", "Not Completed"),
                ],
                max_length=20,
            ),
        ),
    ]
