# Generated by Django 5.1 on 2024-10-06 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalbudgets", "0020_rename_name_category_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="due_date",
            field=models.DateField(default="2024-10-06"),
        ),
        migrations.AlterField(
            model_name="goal",
            name="updated_at",
            field=models.DateField(default="2024-10-06"),
        ),
    ]
