# Generated by Django 5.1 on 2024-10-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalbudgets", "0021_alter_goal_due_date_alter_goal_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="due_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="goal",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="personalbudget",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
