# Generated by Django 5.1 on 2024-10-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "personalbudgets",
            "0022_alter_category_updated_at_alter_goal_due_date_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal",
            old_name="peding_amount",
            new_name="pending_amount",
        ),
    ]
